[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xeaeaea"
yellow = "0xe6c547"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[font]
size = 13

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[scrolling]
history = 10000
